### PR TITLE
BLEMode -> RebootMode

### PR DESCRIPTION
**Pull request by microbit-sam**
RebootMode is now used in BLEManager: BLEMode would never be set!

### CODE REVIEW

**Comment by martinwork** [comment]
When will this be available on the MakeCode beta?

**Comment by microbit-sam** [comment]
@finneyj please can you merge this! :)

**Comment by finneyj** [comment]
Sorry for delay @microbit-sam. Merged.

**Comment by microbit-sam** [comment]
No worries! Does the beta automatically build off this branch or do I need to ask for a MakeCode update?

**Comment by finneyj** [comment]
@martinwork @microbit-sam 

To get onto MakeCode beta we just need to tag new a 2.1.0-rc* here and ask our friends in Redmond to update their reference. They're not building directly off the head of this branch. We planned to do some updates to the memory manager to help claw back some RAM before next release, but if its urgent for testing we can do an interim rc release?

**Comment by martinwork** [comment]
Thanks Joe and Sam. This will enable proper testing of partial flashing with BLE enabled hexes.

**Comment by martinwork** [comment]
Could you please create a new release @finneyj?

**Pull request merged**
